/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package car_service;

import java.sql.*;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bilal
 */
public class ADD_TO_SERVICE extends javax.swing.JFrame {

    private Connection con;
    private Statement st;
    private ResultSet rs;
    private String carwashed;
    DefaultTableModel tbmodel;
    
    
    /**
     * Creates new form ADD_TO_SERVICE
     */
    public ADD_TO_SERVICE() {
        initComponents();
        tname.setEditable(false);
        tvnumber.setEditable(false);
        tvcolor.setEditable(false);
        tdate.setEditable(false);
        sitem.setEditable(false);
        Iprice.setEditable(false);
        tscharge.setEditable(false);
              try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\java\\DBMS\\Car Service.accdb");
            st = con.createStatement();
            rs = st.executeQuery("select * from ACCESSORIES1");
            while (rs.next()) {
                String item = rs.getString("ITEMS");
                String price = rs.getString("PRICE");
                String scharge=rs.getString("SERVICE_CHARGE");
                tbmodel = (DefaultTableModel) jTable1.getModel();
                Object obj[] = {item, price,scharge};
                tbmodel.addRow(obj);}
        } catch (Exception e) {
            System.out.print(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tsid = new javax.swing.JTextField();
        tvnumber = new javax.swing.JTextField();
        tvcolor = new javax.swing.JTextField();
        tdate = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        yesradio = new javax.swing.JRadioButton();
        noradio = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        bsave = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Iprice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        sitem = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tscharge = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD TO SERVICE");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SERVICE ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 90, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VEHICLE NUMBER");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VEHICLE COLOR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DATE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 50, -1));

        tsid.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tsid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tsidMouseClicked(evt);
            }
        });
        tsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsidActionPerformed(evt);
            }
        });
        tsid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tsidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tsidKeyReleased(evt);
            }
        });
        jPanel1.add(tsid, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 190, -1));

        tvnumber.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel1.add(tvnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 190, -1));

        tvcolor.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tvcolor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tvcolorKeyPressed(evt);
            }
        });
        jPanel1.add(tvcolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 190, -1));

        tdate.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tdateFocusGained(evt);
            }
        });
        jPanel1.add(tdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 140, -1));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 43, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        jLabel6.setText("SER");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 2, 60, 50));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("VICE");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 2, 90, 50));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 2, 17)); // NOI18N
        jLabel8.setText("WOULD YOU LIKE TO ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 485, 170, -1));

        buttonGroup1.add(yesradio);
        yesradio.setFont(new java.awt.Font("Trebuchet MS", 2, 17)); // NOI18N
        yesradio.setText("YES");
        yesradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesradioActionPerformed(evt);
            }
        });
        jPanel1.add(yesradio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, -1, -1));

        buttonGroup1.add(noradio);
        noradio.setFont(new java.awt.Font("Trebuchet MS", 2, 17)); // NOI18N
        noradio.setForeground(new java.awt.Color(255, 255, 255));
        noradio.setText("NO");
        noradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noradioActionPerformed(evt);
            }
        });
        jPanel1.add(noradio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, -1, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 2, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("HAVE YOUR CAR WASHED ? ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 485, 230, -1));

        bsave.setFont(new java.awt.Font("Trebuchet MS", 2, 17)); // NOI18N
        bsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/plus.png"))); // NOI18N
        bsave.setText("SAVE");
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });
        jPanel1.add(bsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 130, 30));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SELECT SERVICE");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/left-arrow.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, 33));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/delete (1).png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 50, 30));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/writing (1).png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 50, 30));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SERVICE CHARGE");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        Iprice.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        Iprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IpriceKeyPressed(evt);
            }
        });
        jPanel1.add(Iprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 80, 30));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SELECTED ITEM");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));
        jLabel12.getAccessibleContext().setAccessibleDescription("");

        sitem.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        sitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sitemActionPerformed(evt);
            }
        });
        sitem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sitemKeyPressed(evt);
            }
        });
        jPanel1.add(sitem, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 190, -1));

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Items", "Price", "Service Charge"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.setUpdateSelectionOnSort(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setResizable(false);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 110));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 330, 110));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAME");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/BG6.jpg"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 550));

        tname.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tnameKeyPressed(evt);
            }
        });
        jPanel1.add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 190, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Rs.");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 370, -1, 30));

        tscharge.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tscharge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tschargeKeyPressed(evt);
            }
        });
        jPanel1.add(tscharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 190, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/BG5.jpg"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 450, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void yesradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesradioActionPerformed
        carwashed="yes";
    }//GEN-LAST:event_yesradioActionPerformed

    private void noradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noradioActionPerformed
       carwashed="no";
    }//GEN-LAST:event_noradioActionPerformed

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
        if (tsid.getText().equals("") || tname.getText().equals("")|| tvnumber.getText().equals("") || tvcolor.getText().equals("") || 
                tdate.getText().equals("") || sitem.getText().equals("") || Iprice.getText().equals("") || tscharge.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill all enteries");
        } else {
            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                con = DriverManager.getConnection("jdbc:ucanaccess://D:\\java\\DBMS\\Car service.accdb");
                st = con.createStatement();
                
                if(yesradio.isSelected()){
                    carwashed ="YES"; }
                 if(noradio.isSelected()){
                    carwashed ="NO"; }
                int a = st.executeUpdate("insert into ADD_SERVICE(SID,NAME,V_NUMBER,V_COLOR,DATE,SELECTED_ITEM,ITEM_PRICE,SERVICE_CHARGE,CAR_WASHED) values('" + tsid.getText() + "','"+tname.getText()+"','" + tvnumber.getText() + "','" + tvcolor.getText() + "','" + tdate.getText() + "','"+sitem.getText()+"','"+Iprice.getText()+"','"+tscharge.getText()+"','"+carwashed+"')");
                if (a > 0) {
                    tsid.setText(null);
                    tname.setText(null);
                    tvnumber.setText(null);
                    tvcolor.setText(null);
                    tdate.setText(null);
                    sitem.setText(null);
                    Iprice.setText(null);
                    tscharge.setText(null);
                    tsid.requestFocus();
                    JOptionPane.showMessageDialog(null, "Record saved");
                    STATUS s = new STATUS();
                    s.show();
                    hide();
                    bsave.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Record not saved");
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_bsaveActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        BOOK_SERVICE b = new BOOK_SERVICE();
        b.show();
        hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tsidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tsidMouseClicked
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\java\\DBMS\\Car service.accdb");
            st = con.createStatement();
            rs = st.executeQuery("select * from SERVICE");
            while (rs.next()) {
                tsid.setText(rs.getString("VID"));
                tname.setText(rs.getString("NAME"));
                tvnumber.setText(rs.getString("V_NUMBER"));
                tvcolor.setText(rs.getString("V_COLOR"));
                tdate.setText(rs.getString("DATE"));
               
                bsave.setEnabled(true);
            }
        } catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_tsidMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tsid.setEditable(true);
        tsid.requestFocus();
        tsid.setText(null);
        tname.setText(null);
        tvnumber.setText(null);
        tvcolor.setText(null);
        tdate.setText(null);
        sitem.setText(null);
        Iprice.setText(null);
        tscharge.setText(null);
        bsave.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tsidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tsidKeyReleased
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\java\\DBMS\\Car service.accdb");
            st = con.createStatement();
            rs = st.executeQuery("select * from ADD_SERVICE where SID=" + Integer.parseInt(tsid.getText()) + "");
            if (rs.next()) {
                tname.setText(rs.getString("NAME"));
                tvnumber.setText(rs.getString("V_NUMBER"));
                tvcolor.setText(rs.getString("V_COLOR"));
                tdate.setText(rs.getString("DATE"));
                sitem.setText(rs.getString("SELECTED_ITEM"));
                Iprice.setText(rs.getString("ITEM_PRICE"));
                tscharge.setText(rs.getString("Service_charge"));
            } else {
                JOptionPane.showMessageDialog(null, "Record not found");
                tsid.setText(null);
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_tsidKeyReleased

    private void tdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tdateFocusGained
        try {
            DateFormat df = new SimpleDateFormat();
            tdate.setText(df.format(jDateChooser1.getDate()));
        }catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_tdateFocusGained

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      if (tname.getText().equals("")||tvnumber.getText().equals("") || tvcolor.getText().equals("") || tdate.getText().equals("") || sitem.getText().equals("") || Iprice.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill all enteries");
        } else { try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\java\\DBMS\\Car service.accdb");
            st = con.createStatement();
            int n = st.executeUpdate("Delete from ADD_SERVICE where SID=" + Integer.parseInt(tsid.getText()) + "");
            if (n > 0) {
                tsid.setText(null);
                tname.setText(null);
                tvnumber.setText(null);
                tvcolor.setText(null);
                tdate.setText(null);
                sitem.setText(null);
                Iprice.setText(null);
                tscharge.setText(null);
                JOptionPane.showMessageDialog(null, "Record successfuly delete");
            }
        } catch (Exception e) {
            System.out.print(e);
        }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
bsave.setEnabled(false);
        if (tvnumber.getText().equals("") || tvcolor.getText().equals("") || tdate.getText().equals("") || sitem.getText().equals("") || Iprice.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill all enteries");
        } else {
            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                con = DriverManager.getConnection("jdbc:ucanaccess://D:\\java\\DBMS\\Car service.accdb");
                st = con.createStatement();
                int a = st.executeUpdate("update ADD_SERVICE set  V_NUMBER ='" + tvnumber.getText() + "',V_COLOR ='" + tvcolor.getText() + "',DATE='" + tdate.getText() + "',SELECTED_ITEM='"+sitem.getText()+"',ITEM_PRICE='"+Iprice.getText()+"' where SID='" + Integer.parseInt(tsid.getText()) + "'");
                if (a > 0) {
                    tsid.setText(null);
                    tname.setText(null);
                    tvnumber.setText(null);
                    tvcolor.setText(null);
                    tdate.setText(null);
                    sitem.setText(null);
                    Iprice.setText(null);
                    tscharge.setText(null);
                    tsid.setEnabled(true);
                    tsid.requestFocus();
                    JOptionPane.showMessageDialog(null, "Record saved");
                    bsave.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Record not saved");
                }
            } catch (Exception e) {
                System.out.println(e);}
        }      
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsidActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel tbmodel = (DefaultTableModel) jTable1.getModel();
        int i = jTable1.getSelectedRow();
        if (i >= 0) {
            String item = tbmodel.getValueAt(i, 0).toString();
            String price = tbmodel.getValueAt(i, 1).toString();
            String scharge = tbmodel.getValueAt(i, 2).toString();
            sitem.setText(item);
            Iprice.setText(price);
            tscharge.setText(scharge);
            }
    }//GEN-LAST:event_jTable1MouseClicked

    private void sitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sitemActionPerformed

    private void tsidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tsidKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        
        if(Character.isDigit(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            tsid.setEditable(true);
        }else{
            tsid.setEditable(false);
        }
    }//GEN-LAST:event_tsidKeyPressed

    private void tnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnameKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            tname.setEditable(true);
        }else{
            tname.setEditable(false);
        }
    }//GEN-LAST:event_tnameKeyPressed

    private void tvcolorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tvcolorKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            tvcolor.setEditable(true);
        }else{
            tvcolor.setEditable(false);
        }
    }//GEN-LAST:event_tvcolorKeyPressed

    private void sitemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sitemKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            sitem.setEditable(true);
        }else{
            sitem.setEditable(false);
        }
    }//GEN-LAST:event_sitemKeyPressed

    private void IpriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IpriceKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            Iprice.setEditable(true);
        }else{
            Iprice.setEditable(false);
        }
    }//GEN-LAST:event_IpriceKeyPressed

    private void tschargeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tschargeKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            tscharge.setEditable(true);
        }else{
            tscharge.setEditable(false);
        }
    }//GEN-LAST:event_tschargeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADD_TO_SERVICE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADD_TO_SERVICE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADD_TO_SERVICE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADD_TO_SERVICE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADD_TO_SERVICE().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Iprice;
    private javax.swing.JButton bsave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton noradio;
    private javax.swing.JTextField sitem;
    private javax.swing.JTextField tdate;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tscharge;
    private javax.swing.JTextField tsid;
    private javax.swing.JTextField tvcolor;
    private javax.swing.JTextField tvnumber;
    private javax.swing.JRadioButton yesradio;
    // End of variables declaration//GEN-END:variables

}
