/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package car_service;

import java.sql.*;

/**
 *
 * @author Bilal
 */
public class BILL extends javax.swing.JFrame {

    private Connection con;
    private Statement st;
    private ResultSet rs;

    /**
     * Creates new form BILL
     */
    public BILL() {
        initComponents();
        tsid.requestFocus();
        tsid.setEditable(false);
        tname.setEditable(false);
        tdate.setEditable(false);
        tvnumber.setEditable(false);
        tscharge.setEditable(false);
        ticharge.setEditable(false);
        ttotal.setEditable(false);
        tarea.setEditable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tsid = new javax.swing.JTextField();
        tname = new javax.swing.JTextField();
        tdate = new javax.swing.JTextField();
        tvnumber = new javax.swing.JTextField();
        tscharge = new javax.swing.JTextField();
        ticharge = new javax.swing.JTextField();
        ttotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarea = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BILL");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BILL RECEIPT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 36))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel1.setText("SID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel2.setText("NAME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel3.setText("DATE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel4.setText("VEHICLE NUMBER");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel5.setText("SERVICE CHARGE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel6.setText("ITEM CHARGE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel7.setText("TOTAL");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        tsid.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tsid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tsidMouseClicked(evt);
            }
        });
        jPanel1.add(tsid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 170, -1));

        tname.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel1.add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 170, -1));

        tdate.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel1.add(tdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 170, -1));

        tvnumber.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tvnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvnumberActionPerformed(evt);
            }
        });
        jPanel1.add(tvnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 170, -1));

        tscharge.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel1.add(tscharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 170, -1));

        ticharge.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel1.add(ticharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 170, -1));

        ttotal.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel1.add(ttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 170, -1));

        tarea.setBackground(new java.awt.Color(102, 139, 139));
        tarea.setColumns(20);
        tarea.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tarea.setRows(5);
        jScrollPane1.setViewportView(tarea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 430, 430));

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 140, 40));

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jButton3.setText("PRINT RECEIPT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, 170, 40));

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setText("GENERATE RECEIPT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 250, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
           tarea.setText(tarea.getText()+"------------------------------------------------------------------\n");
           tarea.setText(tarea.getText()+"                              BILL RECEIPT                        \n");
           tarea.setText(tarea.getText()+"------------------------------------------------------------------\n\n");
           tarea.setText(tarea.getText()+"S NO.  :                               "+tsid.getText()+"\n\n");
           tarea.setText(tarea.getText()+"NAME  :                             "+tname.getText()+"\n\n");
           tarea.setText(tarea.getText()+"DATE  :                              "+tdate.getText()+"\n\n");
           tarea.setText(tarea.getText()+"VEHICLE NUMBER  :        "+tvnumber.getText()+"\n\n");
           tarea.setText(tarea.getText()+"SERVICE CHARGE  :         "+tscharge.getText()+"\n\n");
           tarea.setText(tarea.getText()+"ITEM CHARGE  :               "+ticharge.getText()+"\n\n");
           tarea.setText(tarea.getText()+"TOTAL  :                            "+ttotal.getText()+"\n\n");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tvnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvnumberActionPerformed

    private void tsidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tsidMouseClicked
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\java\\DBMS\\Car service.accdb");
            st = con.createStatement();
            rs = st.executeQuery("select * from RETURN");
            while (rs.next()) {
                tsid.setText(rs.getString("SID"));
                tname.setText(rs.getString("NAME"));
                tdate.setText(rs.getString("DATE"));
                tvnumber.setText(rs.getString("V_NUMBER"));
                tscharge.setText(rs.getString("SERVICE_CHARGE"));
                ticharge.setText(rs.getString("ITEM_CHARGE"));
                ttotal.setText(rs.getString("TOTAL"));
            }
        } catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_tsidMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tarea.setText(null);
        tsid.setText(null);
        tname.setText(null);
        tdate.setText(null);
        tvnumber.setText(null);
        tscharge.setText(null);
        ticharge.setText(null);
        ttotal.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try{
    tarea.print();
    RETURN r=new RETURN();
    r.show();
    hide();
}catch(Exception e){
    System.out.print(e);
}
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BILL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BILL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BILL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BILL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BILL().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tarea;
    private javax.swing.JTextField tdate;
    private javax.swing.JTextField ticharge;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tscharge;
    private javax.swing.JTextField tsid;
    private javax.swing.JTextField ttotal;
    private javax.swing.JTextField tvnumber;
    // End of variables declaration//GEN-END:variables
}
