/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package car_service;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author Bilal
 */
public class BOOK_SERVICE extends javax.swing.JFrame {
   private Connection con;
   private Statement st;
   private ResultSet rs;
   
    /**
     * Creates new form BOOK_SERVICE
     */
    public BOOK_SERVICE() {
        initComponents();
        tvid.setEditable(false);
        tname.setEditable(false);
        tdate.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tvid = new javax.swing.JTextField();
        tname = new javax.swing.JTextField();
        tvnumber = new javax.swing.JTextField();
        tvmodel = new javax.swing.JTextField();
        tvcolor = new javax.swing.JTextField();
        tdate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        bsave = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bdelete = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tcombo = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VEHICLE DETAILS");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VEHICLE ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("OWNER NAME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VEHICLE NUMBER");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("VEHICLE MODEL ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("VEHICLE COLOR");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DATE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        tvid.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tvid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tvidFocusGained(evt);
            }
        });
        tvid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvidMouseClicked(evt);
            }
        });
        tvid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvidActionPerformed(evt);
            }
        });
        tvid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tvidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tvidKeyReleased(evt);
            }
        });
        jPanel1.add(tvid, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 180, -1));

        tname.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tnameKeyPressed(evt);
            }
        });
        jPanel1.add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 180, -1));

        tvnumber.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel1.add(tvnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 180, -1));

        tvmodel.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tvmodel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tvmodelKeyPressed(evt);
            }
        });
        jPanel1.add(tvmodel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 180, -1));

        tvcolor.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tvcolor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tvcolorKeyPressed(evt);
            }
        });
        jPanel1.add(tvcolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 180, -1));

        tdate.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tdateFocusGained(evt);
            }
        });
        jPanel1.add(tdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 130, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 2, 32)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("VEHICLE");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 140, 40));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 2, 32)); // NOI18N
        jLabel8.setText("DETAILS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 130, 30));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 2, 32)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 0));
        jLabel9.setText("VEHICLE");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, 30));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 2, 32)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 51));
        jLabel10.setText("DETAILS");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 130, -1));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 40, -1));

        bsave.setBackground(new java.awt.Color(0, 102, 0));
        bsave.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        bsave.setText("SAVE");
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });
        jPanel1.add(bsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 180, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/left-arrow.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 100, 30));

        bdelete.setFont(new java.awt.Font("Trebuchet MS", 2, 17)); // NOI18N
        bdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/delete (1).png"))); // NOI18N
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });
        jPanel1.add(bdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 90, -1));

        bedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/writing (1).png"))); // NOI18N
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });
        jPanel1.add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 80, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 100, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("BRAND");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        tcombo.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        tcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "------Select------", "Nissan", "Honda", "KIA", "mahindra", "Suzuki", "TATA ", "Hundai Motor Company", "Toyota", "Ford", "BMW", "Audi", "Volkswagen", "Mercedes-Benz", "Ferrari", "Porche", "Tesla", "Chevrolet", "Lamborghini", "Jaguar", "Bentley", "Jeep", " " }));
        tcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcomboActionPerformed(evt);
            }
        });
        jPanel1.add(tcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 180, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/BG3.jpg"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 450, 540));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/BG.jpg"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tvidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvidActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       HOME H=new HOME();
       H.show();
       hide();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
        bsave.setEnabled(false);
        if (tname.getText().equals("") || tvnumber.getText().equals("") || tvmodel.getText().equals("") || tvcolor.getText().equals("")||tcombo.getSelectedItem().equals("") || tdate.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill all enteries");
        } else { try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\java\\DBMS\\Car service.accdb");
            st = con.createStatement();
            int n = st.executeUpdate("Delete from SERVICE where VID=" + Integer.parseInt(tvid.getText()) + "");
            if (n > 0) {
                tvid.setText(null);
                tname.setText(null);
                tvnumber.setText(null);
                tvmodel.setText(null);
                tvcolor.setText(null);
                tcombo.setSelectedIndex(0);
                tdate.setText(null);
                JOptionPane.showMessageDialog(null, "Record successfuly delete");
            }
        } catch (Exception e) {
            System.out.print(e);
        }
        }
    }//GEN-LAST:event_bdeleteActionPerformed

    private void tdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tdateFocusGained
            try { DateFormat df=new SimpleDateFormat("dd-mm-yyyy");
                 tdate.setText(df.format(jDateChooser1.getDate()));
                } catch(Exception e){
                    System.out.print(e);
                }
    }//GEN-LAST:event_tdateFocusGained

    private void tvidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvidMouseClicked
       try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\java\\DBMS\\Car service.accdb");
            st = con.createStatement();
            rs = st.executeQuery("select * from CUSTOMER");
            while (rs.next()) {
                   tvid.setText(rs.getString("CID"));
                   tname.setText(rs.getString("NAME"));
                   tdate.setText(rs.getString("DATE"));
                   bsave.setEnabled(true);
                   tvnumber.requestFocus();
                }
        } catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_tvidMouseClicked

    private void tvidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tvidFocusGained

    }//GEN-LAST:event_tvidFocusGained

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
if (tvid.getText().equals("") || tname.getText().equals("") || tvnumber.getText().equals("") || tvmodel.getText().equals("") || tvcolor.getText().equals("")||tcombo.getSelectedItem().equals("") || tdate.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill all enteries");
        } else {
            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                con = DriverManager.getConnection("jdbc:ucanaccess://D:\\java\\DBMS\\Car service.accdb");
                st = con.createStatement();
                int a = st.executeUpdate("insert into SERVICE values('" + tvid.getText() + "','" + tname.getText() + "','" + tvnumber.getText() + "','" + tvmodel.getText() + "','" + tvcolor.getText() + "','"+tcombo.getSelectedItem().toString()+"','" + tdate.getText() + "')");
                if (a > 0) {
                    tvid.setText(null);
                    tname.setText(null);
                    tvnumber.setText(null);
                    tvmodel.setText(null);
                    tvcolor.setText(null);
                    tcombo.setSelectedIndex(0);
                    tdate.setText(null);
                    tvid.setEnabled(true);
                    tvid.requestFocus();
                    JOptionPane.showMessageDialog(null, "Record saved");
                    ADD_TO_SERVICE ad=new ADD_TO_SERVICE();
                    ad.show();
                    hide();
                    bsave.setEnabled(false);
                  } else {
                    JOptionPane.showMessageDialog(null, "Record not saved");}
            } catch (Exception e) {
                System.out.println(e);
            }
        }

    }//GEN-LAST:event_bsaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tvid.setEditable(true);
        tvid.requestFocus();
        tvid.setText(null);
        tname.setText(null);
        tvnumber.setText(null);
        tvmodel.setText(null);
        tvcolor.setText(null);
        tdate.setText(null);
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tvidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tvidKeyReleased
                try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\java\\DBMS\\Car service.accdb");
            st = con.createStatement();
            rs = st.executeQuery("select * from SERVICE where VID=" + Integer.parseInt(tvid.getText()) + "");
            if (rs.next()) {
                tname.setText(rs.getString("NAME"));
                tvnumber.setText(rs.getString("V_NUMBER"));
                tvmodel.setText(rs.getString("V_MODEL"));
                tvcolor.setText(rs.getString("V_COLOR"));
                tcombo.setSelectedItem(rs.getString("BRAND"));
                tdate.setText(rs.getString("DATE"));
            } else {
                JOptionPane.showMessageDialog(null, "Record not found");
                tvid.setText(null);
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_tvidKeyReleased

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
 bsave.setEnabled(false);
        if (tname.getText().equals("") || tvnumber.getText().equals("") || tvmodel.getText().equals("") || tvcolor.getText().equals("")||tcombo.getSelectedItem().equals("") || tdate.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill all enteries");
        } else {
            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                con = DriverManager.getConnection("jdbc:ucanaccess://D:\\java\\DBMS\\Car service.accdb");
                st = con.createStatement();
                int a = st.executeUpdate("update SERVICE set  NAME ='" + tname.getText() + "',V_NUMBER ='" + tvnumber.getText() + "',V_MODEL='" + tvmodel.getText() + "',V_COLOR='" + tvcolor.getText() + "',BRAND='"+tcombo.getToolTipText()+"', DATE ='" + tdate.getText() + "' where VID='" + Integer.parseInt(tvid.getText()) + "'");
                if (a > 0) {
                    tvid.setText(null);
                    tname.setText(null);
                    tvnumber.setText(null);
                    tvmodel.setText(null);
                    tvcolor.setText(null);
                    tcombo.setSelectedIndex(0);
                    tdate.setText(null);
                    tvid.setEnabled(true);
                    tvid.requestFocus();
                    JOptionPane.showMessageDialog(null, "Record saved");
                    bsave.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Record not saved");
                }
            } catch (Exception e) {
                System.out.println(e);}
        }
    }//GEN-LAST:event_beditActionPerformed

    private void tcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcomboActionPerformed

    private void tvidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tvidKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        
        if(Character.isDigit(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            tvid.setEditable(true);
        }else{
            tvid.setEditable(false);
        }
    }//GEN-LAST:event_tvidKeyPressed

    private void tnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnameKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            tname.setEditable(true);
        }else{
            tname.setEditable(false);
        }
    }//GEN-LAST:event_tnameKeyPressed

    private void tvmodelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tvmodelKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        
        if(Character.isDigit(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            tvmodel.setEditable(true);
        }else{
            tvmodel.setEditable(false);
        }
    }//GEN-LAST:event_tvmodelKeyPressed

    private void tvcolorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tvcolorKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            tvcolor.setEditable(true);
        }else{
            tvcolor.setEditable(false);
        }
    }//GEN-LAST:event_tvcolorKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BOOK_SERVICE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BOOK_SERVICE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BOOK_SERVICE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BOOK_SERVICE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BOOK_SERVICE().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdelete;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bsave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox tcombo;
    private javax.swing.JTextField tdate;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tvcolor;
    private javax.swing.JTextField tvid;
    private javax.swing.JTextField tvmodel;
    private javax.swing.JTextField tvnumber;
    // End of variables declaration//GEN-END:variables
}
