/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package car_service;

import java.sql.*;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

public class Forget_Password extends javax.swing.JFrame {
    private Connection con;
    private Statement st;
    private ResultSet rs;

    /**
     * Creates new form Forget_Password
     */
    public Forget_Password() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tuser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tsec = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        tepass = new javax.swing.JPasswordField();
        tcpass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forget Password");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\java\\image\\R (1).png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 257, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel3.setText("Trouble Logging in?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 234, -1));

        tuser.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        tuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuserActionPerformed(evt);
            }
        });
        jPanel1.add(tuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 270, 30));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setText("Enter Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        jButton2.setBackground(new java.awt.Color(5, 194, 168));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jButton2.setText("Create New User");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, 267, -1));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/ForgetPassword.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 590));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel9.setText("User Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("Security Answer");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        tsec.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        tsec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsecActionPerformed(evt);
            }
        });
        tsec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tsecKeyReleased(evt);
            }
        });
        jPanel1.add(tsec, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 220, -1));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel10.setText("Confirm Password");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, -1, -1));

        jButton1.setBackground(new java.awt.Color(177, 34, 38));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 270, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/1Search-icon.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 40, 30));

        tepass.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        jPanel1.add(tepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 270, -1));

        tcpass.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        jPanel1.add(tcpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 270, -1));

        jLabel5.setText("---------------------OR-------------------------");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuserActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Signup ss = new Signup();
        ss.show();
        hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        LOGIN l1 = new LOGIN();
        l1.show();
        hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tsecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsecActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tsec.getText().equals("") || tuser.getText().equals("") || tepass.getText().equals("") || tcpass.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill all enteries");
        } else {
            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                con = DriverManager.getConnection("jdbc:ucanaccess://D:\\java\\DBMS\\Car service.accdb");
                st = con.createStatement();
                int a = st.executeUpdate("update LOGINSIGNUP set USER_NAME ='" + tuser.getText() + "',PASSWORD ='" + tepass.getText() + "',CONFIRM_PASSWORD ='" + tcpass.getText() + "' where SECURITY_ANSWER='" + tsec.getText() + "'");
                if (a > 0) {
                    tsec.setText(null); 
                    tuser.setText(null);
                    tepass.setText(null);
                    tcpass.setText(null);
                    tsec.requestFocus();
                    JOptionPane.showMessageDialog(null, "Record saved");
                } else {
                    JOptionPane.showMessageDialog(null, "Record not saved");
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tsecKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tsecKeyReleased
    }//GEN-LAST:event_tsecKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\java\\DBMS\\Car service.accdb");
            st = con.createStatement();
            rs = st.executeQuery("select * from LOGINSIGNUP where SECURITY_ANSWER='" + tsec.getText() + "'");
            if (rs.next()) {
                tuser.setText(rs.getString("USER_NAME"));
            } else {
                JOptionPane.showMessageDialog(null, "Record not found");
                tsec.setText(null);
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forget_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forget_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forget_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forget_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forget_Password().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField tcpass;
    private javax.swing.JPasswordField tepass;
    private javax.swing.JTextField tsec;
    private javax.swing.JTextField tuser;
    // End of variables declaration//GEN-END:variables
}
