/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package car_service;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Bilal
 */
public class LOGIN extends javax.swing.JFrame {

    private Connection con;
    private Statement st;
    private ResultSet rs;

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tuser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ppass = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        tu2 = new javax.swing.JLabel();
        jcombo = new javax.swing.JCheckBox();
        tu1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 70));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USER NAME");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        tuser.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tuserMouseClicked(evt);
            }
        });
        jPanel2.add(tuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 200, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PASSWORD");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        ppass.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        ppass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ppassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ppassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ppassMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ppassMousePressed(evt);
            }
        });
        jPanel2.add(ppass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 200, -1));

        login.setBackground(new java.awt.Color(0, 102, 0));
        login.setFont(new java.awt.Font("Trebuchet MS", 2, 17)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel2.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 200, -1));

        jButton3.setBackground(new java.awt.Color(0, 102, 153));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 2, 17)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SIGNUP");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 102, 153));
        jButton4.setFont(new java.awt.Font("Trebuchet MS", 2, 17)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("FORGET PASSWORD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 200, -1));

        tu2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tu2.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(tu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 30, 30));

        jcombo.setForeground(new java.awt.Color(255, 255, 255));
        jcombo.setText("SHOW PASSWORD");
        jcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboActionPerformed(evt);
            }
        });
        jPanel2.add(jcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        tu1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tu1.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(tu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 130, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 340, 430));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/BGG.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Signup s = new Signup();
        s.show();
        hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Forget_Password fp = new Forget_Password();
        fp.show();
        hide();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
//LOGIN
        if (tuser.getText().equals("")) {
            tuser.setText("?"); } 
            if (ppass.getText().equals("")) {
                ppass.setText("?");
            } else {
                try {
                    Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                    con = DriverManager.getConnection("jdbc:ucanaccess://D:\\java\\DBMS\\Car service.accdb");
                    st = con.createStatement();
                    rs = st.executeQuery("select * from LOGINSIGNUP");
                    if (rs.next()) {
                        if (tuser.getText().equals(rs.getString("USER_NAME")) && ppass.getText().equals(rs.getString("PASSWORD"))) {
                            WELCOME w = new WELCOME();
                            w.show();
                            hide();
                        } else {
                            JOptionPane.showMessageDialog(null, "INVALID USER NAME AND PASSWORD");
                            tuser.setText(null);
                            ppass.setText(null);
                            tuser.requestFocus();
                        }
                    }
                } catch (Exception e) {
                    System.out.print(e);
                }
            }
        

    }//GEN-LAST:event_loginActionPerformed

    private void jcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboActionPerformed
        if (jcombo.isSelected()) {
            ppass.setEchoChar((char) 0);
        } else {
            ppass.setEchoChar('*');
        }
    }//GEN-LAST:event_jcomboActionPerformed

    private void tuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tuserMouseClicked
                tuser.setText(null);
                
    }//GEN-LAST:event_tuserMouseClicked

    private void ppassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppassMouseClicked
           ppass.setText(null);
    }//GEN-LAST:event_ppassMouseClicked

    private void ppassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppassMouseEntered
            
    }//GEN-LAST:event_ppassMouseEntered

    private void ppassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppassMousePressed
       // TODO add your handling code here:
    }//GEN-LAST:event_ppassMousePressed

    private void ppassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppassMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ppassMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JCheckBox jcombo;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField ppass;
    private javax.swing.JLabel tu1;
    private javax.swing.JLabel tu2;
    private javax.swing.JTextField tuser;
    // End of variables declaration//GEN-END:variables
}
;