/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package car_service;

import java.sql.DriverManager;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bilal
 */
public class Signup extends javax.swing.JFrame {

    private Connection con;
    private Statement st;
    private ResultSet rs;

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfirst = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tsecond = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tuser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tpass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        tcpass = new javax.swing.JPasswordField();
        tcombo = new javax.swing.JComboBox();
        tans = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        bcreate = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Signup");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 100, 20));

        tfirst.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfirstActionPerformed(evt);
            }
        });
        tfirst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfirstKeyPressed(evt);
            }
        });
        jPanel1.add(tfirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 210, 30));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, 22));

        tsecond.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tsecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsecondActionPerformed(evt);
            }
        });
        tsecond.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tsecondKeyPressed(evt);
            }
        });
        jPanel1.add(tsecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 210, 30));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        tuser.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuserActionPerformed(evt);
            }
        });
        tuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tuserKeyPressed(evt);
            }
        });
        jPanel1.add(tuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 210, 30));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        tpass.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpassActionPerformed(evt);
            }
        });
        jPanel1.add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 210, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirm Password:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        tcpass.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel1.add(tcpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 210, 30));

        tcombo.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        tcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "------Select------", "What is your DOB ", "What is your Nationality", "what is your father name", "what is your hobby" }));
        tcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcomboActionPerformed(evt);
            }
        });
        jPanel1.add(tcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 210, 30));

        tans.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tansActionPerformed(evt);
            }
        });
        jPanel1.add(tans, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 210, 30));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Security Question:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Answer:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/left-arrow.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 130, 35));

        bcreate.setBackground(new java.awt.Color(48, 176, 48));
        bcreate.setFont(new java.awt.Font("Trebuchet MS", 2, 20)); // NOI18N
        bcreate.setText("Create");
        bcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcreateActionPerformed(evt);
            }
        });
        jPanel1.add(bcreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 180, -1));

        jCheckBox1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show Answer");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SIGN");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/BG7.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 500));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 204));
        jLabel11.setText("UP");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/BG1.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 460, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfirstActionPerformed

    private void tuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuserActionPerformed

    private void tpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpassActionPerformed

    private void tansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tansActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LOGIN l2 = new LOGIN();
        l2.show();
        hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tsecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsecondActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsecondActionPerformed

    private void tcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcomboActionPerformed

    private void bcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcreateActionPerformed
        if (tfirst.getText().equals("") || tsecond.getText().equals("") || tuser.getText().equals("") || tpass.getText().equals("") || tcpass.getText().equals("") || tcombo.getSelectedItem().equals("") || tans.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill all enteries");
        } else {
            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                con = DriverManager.getConnection("jdbc:ucanaccess://D:\\java\\DBMS\\Car service.accdb");
                st = con.createStatement();
                int a = st.executeUpdate("insert into LOGINSIGNUP (FIRST_NAME,LAST_NAME,USER_NAME,PASSWORD,CONFIRM_PASSWORD,SECURITY_QUESTION,SECURITY_ANSWER) values('" + tfirst.getText() + "','" + tsecond.getText() + "','" + tuser.getText() + "','" + tpass.getText() + "','" + tcpass.getText() + "','" + tcombo.getSelectedItem() + "','" + tans.getText() + "')");
                if (a > 0) {
                    tfirst.setText(null);
                    tsecond.setText(null);
                    tuser.setText(null);
                    tpass.setText(null);
                    tcpass.setText(null);
                    tcombo.setSelectedIndex(0);
                    tans.setText(null);
                    tfirst.requestFocus();
                    JOptionPane.showMessageDialog(null, "Record saved");
                } else {
                    JOptionPane.showMessageDialog(null, "Record not saved");
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_bcreateActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            tans.setEchoChar((char) 0);
        } else {
            tans.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void tfirstKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfirstKeyPressed
        // TODO add your handling code here:
           //code for jtextfield that accept letter ,whitespace and delete backspace key only
        char c=evt.getKeyChar();
        
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            //iso control for edit operation(delete key and backspace key allow)
            //if enter character is letter,space and iso control char than allow to edit
            tfirst.setEditable(true);
        }else{
            tfirst.setEditable(false);
        }
    }//GEN-LAST:event_tfirstKeyPressed

    private void tsecondKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tsecondKeyPressed
        // TODO add your handling code here:
         //code for jtextfield that accept letter ,whitespace and delete backspace key only
        char c=evt.getKeyChar();
        
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            //iso control for edit operation(delete key and backspace key allow)
            //if enter character is letter,space and iso control char than allow to edit
            tsecond.setEditable(true);
        }else{
            tsecond.setEditable(false);
        }
    }//GEN-LAST:event_tsecondKeyPressed

    private void tuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tuserKeyPressed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_tuserKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcreate;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField tans;
    private javax.swing.JComboBox tcombo;
    private javax.swing.JPasswordField tcpass;
    private javax.swing.JTextField tfirst;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JTextField tsecond;
    private javax.swing.JTextField tuser;
    // End of variables declaration//GEN-END:variables
}
