/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package car_service;

import java.sql.*;
import javax.swing.JOptionPane;
import java.text.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bilal
 */
public class STATUS extends javax.swing.JFrame {

    private Connection con;
    private Statement st;
    private ResultSet rs;
    private String Result;
    
    /**
     * Creates new form STATUS
     */
    public STATUS() {
        initComponents();
        tsid.setEditable(false);
        tname.setEditable(false);
        tvnumber.setEditable(false);
        
        tsid.setEditable(false);
        tname.setEditable(false);
        tvnumber.setEditable(false);
        tscharge.setEditable(false);
        ticharge.setEditable(false);
        ttotal.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rcomplete = new javax.swing.JRadioButton();
        rincomplete = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tsid = new javax.swing.JTextField();
        tname = new javax.swing.JTextField();
        tvnumber = new javax.swing.JTextField();
        tdate = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        tndate = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        breturn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tscharge = new javax.swing.JTextField();
        ticharge = new javax.swing.JTextField();
        ttotal = new javax.swing.JTextField();
        td1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STATUS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(111, 164, 164));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STATUS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 2, 36))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel1.setText("SERVICE STATUS");

        buttonGroup1.add(rcomplete);
        rcomplete.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        rcomplete.setSelected(true);
        rcomplete.setText("COMPLETE");
        rcomplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcompleteActionPerformed(evt);
            }
        });

        buttonGroup1.add(rincomplete);
        rincomplete.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        rincomplete.setText("INCOMPLETE");
        rincomplete.setEnabled(false);
        rincomplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rincompleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rincomplete)
                    .addComponent(rcomplete))
                .addContainerGap(372, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rcomplete))
                .addGap(18, 18, 18)
                .addComponent(rincomplete)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(154, 67, 67));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RECEIVE YOUR CAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 2, 36), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SERVICE ID");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CUSTOMER NAME");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("VEHICLE NUMBER");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DATE");

        tsid.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tsid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tsidFocusGained(evt);
            }
        });
        tsid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tsidMouseClicked(evt);
            }
        });
        tsid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tsidKeyPressed(evt);
            }
        });

        tname.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        tvnumber.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        tdate.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tdateFocusGained(evt);
            }
        });
        tdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tdateMouseClicked(evt);
            }
        });
        tdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdateActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NEXT SERVICE");

        tndate.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tndate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tndateFocusGained(evt);
            }
        });

        breturn.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        breturn.setText("RETURN TO CUSTOMER");
        breturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breturnActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/left-arrow.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SERVICE CHARGE");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ITEM PRICE");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TOTAL");

        tscharge.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        ticharge.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        ttotal.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        ttotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ttotalFocusGained(evt);
            }
        });
        ttotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttotalMouseClicked(evt);
            }
        });

        td1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(breturn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addComponent(tvnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tsid, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tdate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(td1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tndate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 3, Short.MAX_VALUE))
                            .addComponent(tscharge)
                            .addComponent(ticharge)
                            .addComponent(ttotal))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(ticharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(tdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(ttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tsid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(tscharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(td1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tvnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tndate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(breturn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ADD_TO_SERVICE a = new ADD_TO_SERVICE();
        a.show();
        hide();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void tdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdateActionPerformed

    private void breturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breturnActionPerformed
        if(tdate.getText().equals("")){
            td1.setText("Please enter date");
        }
        if (tsid.getText().equals("") || tname.getText().equals("") || tdate.getText().equals("") || tvnumber.getText().equals("")||tscharge.getText().equals("")||ticharge.getText().equals("")|| ttotal.getText().equals("") ||  tndate.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill all enteries");
        } else {
            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                con = DriverManager.getConnection("jdbc:ucanaccess://D:\\java\\DBMS\\Car service.accdb");
                st = con.createStatement();
              
                if (rcomplete.isSelected()) {
                    Result = "COMPLETE";   }
               
                if (rincomplete.isSelected()) {
                    Result = "INCOMPLETE";   }
               
                int a = st.executeUpdate("insert into RETURN values('" + tsid.getText() + "','"+tscharge.getText()+"','" + tname.getText() + "','"+ticharge.getText()+"','" + tdate.getText() + "','"+ttotal.getText()+"','" + tvnumber.getText() + "','" + tndate.getText() + "','" + Result + "')");
                if (a > 0) {
                    tsid.setText(null);
                    tname.setText(null);
                    tdate.setText(null);
                    tvnumber.setText(null);
                    tscharge.setText(null);
                    ticharge.setText(null);
                    ttotal.setText(null);
                    tndate.setText(null);
                    tsid.requestFocus();
                    JOptionPane.showMessageDialog(null, "Record saved");
                    BILL r = new BILL();
                    r.show();
                    hide();
                    breturn.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Record not saved");
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_breturnActionPerformed

    private void rcompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcompleteActionPerformed
        Result = "COMPLETE";
    }//GEN-LAST:event_rcompleteActionPerformed

    private void rincompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rincompleteActionPerformed
        Result = "INCOMPLETE";
    }//GEN-LAST:event_rincompleteActionPerformed

    private void tsidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tsidFocusGained
    }//GEN-LAST:event_tsidFocusGained

    private void tsidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tsidMouseClicked
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\java\\DBMS\\Car service.accdb");
            st = con.createStatement();
            rs = st.executeQuery("select * from ADD_SERVICE");
            while (rs.next()) {
                tsid.setText(rs.getString("SID"));
                tname.setText(rs.getString("NAME"));
                tvnumber.setText(rs.getString("V_NUMBER"));
                ticharge.setText(rs.getString("ITEM_PRICE"));
                tscharge.setText(rs.getString("SERVICE_CHARGE"));
                
                double a,b,c;
                  a=Double.parseDouble(tscharge.getText());
                  b=Double.parseDouble(ticharge.getText());
                  c=a+b;
                  ttotal.setText(Double.toString(c));
                  if(tdate.getText().equals("")){
            td1.setText("Please enter date");
        }
            }
        } catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_tsidMouseClicked

    private void tndateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tndateFocusGained
        try {
            DateFormat df = new SimpleDateFormat();
            tndate.setText(df.format(jDateChooser2.getDate()));
        } catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_tndateFocusGained

    private void tdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tdateFocusGained
        try {
            DateFormat df = new SimpleDateFormat();
             tdate.setText(null);
            tdate.setText(df.format(jDateChooser1.getDate()));
           
        } catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_tdateFocusGained

    private void ttotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttotalMouseClicked
        double a,b,c;
        a=Double.parseDouble(tscharge.getText());
        b=Double.parseDouble(ticharge.getText());
        c=a+b;
        ttotal.setText(Double.toString(c));
    }//GEN-LAST:event_ttotalMouseClicked

    private void ttotalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ttotalFocusGained
        double a,b,c;
        a=Double.parseDouble(tscharge.getText());
        b=Double.parseDouble(ticharge.getText());
        c=a+b;
        ttotal.setText(Double.toString(c));
    }//GEN-LAST:event_ttotalFocusGained

    private void tdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdateMouseClicked
tdate.setText(null);        // TODO add your handling code here:
    }//GEN-LAST:event_tdateMouseClicked

    private void tsidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tsidKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        
        if(Character.isDigit(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            tname.setEditable(true);
        }else{
            tname.setEditable(false);
        }
    }//GEN-LAST:event_tsidKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(STATUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(STATUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(STATUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(STATUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new STATUS().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton breturn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rcomplete;
    private javax.swing.JRadioButton rincomplete;
    private javax.swing.JLabel td1;
    private javax.swing.JTextField tdate;
    private javax.swing.JTextField ticharge;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tndate;
    private javax.swing.JTextField tscharge;
    private javax.swing.JTextField tsid;
    private javax.swing.JTextField ttotal;
    private javax.swing.JTextField tvnumber;
    // End of variables declaration//GEN-END:variables
}
